name             'undef-collectd'
maintainer       'Greg Albrecht'
maintainer_email 'oss@undef.net'
license          'All rights reserved'
description      'Installs/Configures undef-collectd'
long_description 'Installs/Configures undef-collectd'
version          '1.0.0'

depends 'collectd', '~> 2.2.2'
depends 'collectd_plugins', '~> 2.1.3'
